// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Panell.Models;

#nullable disable

namespace Panell.Migrations
{
    [DbContext(typeof(SayfaContext))]
    [Migration("20221230145910_myDatams")]
    partial class myDatams
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Panell.Models.Diller", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("dil_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dil_kisaltma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Diller");
                });

            modelBuilder.Entity("Panell.Models.Dsayfalar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("baglantili_dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baglantili_sayfa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_kategori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_ozet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_tarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dsayfalar");
                });

            modelBuilder.Entity("Panell.Models.Galeri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("gelen_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Galeri");
                });

            modelBuilder.Entity("Panell.Models.Iletisim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("favicon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("google")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("youtube")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Iletisim");
                });

            modelBuilder.Entity("Panell.Models.Mesaj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mesaj");
                });

            modelBuilder.Entity("Panell.Models.Sayfalar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("sayfa_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_kategori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_ozet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_resimm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_tarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sayfa_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sayfalar");
                });

            modelBuilder.Entity("Panell.Models.Temsilci", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Temsilci");
                });

            modelBuilder.Entity("Panell.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("user_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
